/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mike
 */
package proyecto;

import java.awt.Container;

import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class GUI extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form GUI
	 */
	public GUI(Controller controller) {
		this.controller = controller;
		initComponents();

	}

	private void displayButtonPrompt(){
		//    	productos.setModel(new javax.swing.AbstractListModel() {
		//            String[] strings = { "Paquete lubricante", "Estearato de calcio", "Estearato de zinc", "Estearato de magnesio", "Estearato de sodio" };
		//            public int getSize() { return strings.length; }
		//            public Object getElementAt(int i) { return strings[i]; }
		//        });

		buttonPrompt.setVisible(true);

		/*buttonPrompt.setVisible(true);
    	final javax.swing.JButton cancelar = new JButton();
    	cancelar.setText("Cancelar");
    	cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	Container frame = cancelar.getParent();
				do
					frame = frame.getParent();
				while (!(frame instanceof JFrame));
				((JFrame) frame).dispose();
            }
    	});

    	boolean valid;
    	do{
    		valid = true;
	    	final JComponent[] inputs = new JComponent[] {
	    			new JLabel("Numero de batch: "),
	    			batch,
	    			new JLabel("Producto: "),
	    			productos,
	    			cancelar
	    	};

	    	JOptionPane.showMessageDialog(null, inputs, "Especificaciones", JOptionPane.PLAIN_MESSAGE);

	    	System.out.println("You entered " +
	    			batch.getText() + ", " +
	    			productos.getSelectedValue());

	    	System.out.println(batch.getText());
	    	System.out.println(productos.getSelectedIndex());

	    	if(batch.getText().equals(""))
	    		valid = !valid;
	    	if(productos.getSelectedIndex() == -1)
	    		valid = !valid;
	    	try{
	    		Integer.parseInt(batch.getText());
	    	}catch(Exception e){
	    		if(!batch.getText().equals(""))
	    			valid = false;
	    	}

    	}while(!valid);*/
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		form = new Form();
		batch = new JTextField();
		productos = new JList();
		buttonPrompt = new ButtonPrompt(form);

		filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100), new java.awt.Dimension(32767, 100));
		
		pelletizador = Planta.getMaquinaPorNombre("Pelletizador").getButton();
		
		reactor1 = Planta.getMaquinaPorNombre("Reactor 1").getButton();
		reactor2 = Planta.getMaquinaPorNombre("Reactor 2").getButton();
		reactor3 = Planta.getMaquinaPorNombre("Reactor 3").getButton();
		reactor4 = Planta.getMaquinaPorNombre("Reactor 4").getButton();
		reactor5 = Planta.getMaquinaPorNombre("Reactor 5").getButton();
		
		tanqueCera = Planta.getMaquinaPorNombre("Tanque cera").getButton();
		tanqueEstearina = Planta.getMaquinaPorNombre("Tanque estearina").getButton();

		molino1 = Planta.getMaquinaPorNombre("Molino 1").getButton();
		molino5 = Planta.getMaquinaPorNombre("Molino 5").getButton();
		
		rt1 = Planta.getMaquinaPorNombre("Rompeterrones 1").getButton();
		
		criba2 = Planta.getMaquinaPorNombre("Criba 2").getButton();
		

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		pelletizador.setText("Pelletizador");
		pelletizador.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				pelletizadorMouseClicked(evt);
			}
		});

		reactor4.setText("Reactor 4");
		reactor4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				reactor4MouseClicked(evt);
			}
		});

		reactor2.setText("Reactor 2");
		reactor2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				reactor2MouseClicked(evt);
			}
		});

		reactor3.setText("Reactor 3");
		reactor3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				reactor3MouseClicked(evt);
			}
		});

		tanqueCera.setText("Tanque cera");
		tanqueCera.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tanqueCeraMouseClicked(evt);
			}
		});

		tanqueEstearina.setText("Tanque estearina");
		tanqueEstearina.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tanqueEstearinaMouseClicked(evt);
			}
		});

		molino1.setText("Molino 1");
		molino1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				molino1MouseClicked(evt);
			}
		});

		rt1.setText("Rompeterrones 1");
		rt1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				rt1MouseClicked(evt);
			}
		});

		criba2.setText("Criba PF-02");
		criba2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				criba2MouseClicked(evt);
			}
		});

		molino5.setText("Molino 5");
		molino5.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				molino5MouseClicked(evt);
			}
		});

		reactor5.setText("R5");
		reactor5.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				reactor5MouseClicked(evt);
			}
		});

		reactor1.setText("R1");
		reactor1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				reactor1MouseClicked(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(molino5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(criba2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(rt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(tanqueEstearina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
								.addComponent(tanqueCera, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(pelletizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(molino1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(reactor5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(reactor1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
														.addComponent(reactor4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
														.addComponent(reactor3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(reactor2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 908, Short.MAX_VALUE)
														.addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(298, 298, 298))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGap(75, 75, 75)
										.addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(pelletizador, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
																.addComponent(reactor4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(reactor3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(reactor2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGroup(layout.createSequentialGroup()
																		.addComponent(reactor5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(reactor1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(tanqueCera, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(tanqueEstearina, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(molino1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(rt1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(criba2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(molino5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap(104, Short.MAX_VALUE))
				);

		pack();
	}// </editor-fold>                        

	private void pelletizadorMouseClicked(java.awt.event.MouseEvent evt) {
		Maquina actual = Planta.getMaquinaPorNombre("Pelletizador");

		if(!actual.estaEnUso())
		{
			displayButtonPrompt();

			if(form.getBatch() == 0 || form.getProducto().equals(""))
				return;

			controller.updateAfterPrompt(actual, form);
		}
		else {
			controller.updateToNextStep(actual);
		}
		
	}                                         

	private void reactor1MouseClicked(java.awt.event.MouseEvent evt) {                                      
		// TODO add your handling code here:
	}                                     

	private void reactor2MouseClicked(java.awt.event.MouseEvent evt) {                                      
		// TODO add your handling code here:
	}                                     

	private void reactor3MouseClicked(java.awt.event.MouseEvent evt) {                                      
		// TODO add your handling code here:
	}                                     

	private void reactor4MouseClicked(java.awt.event.MouseEvent evt) {                                      
		// TODO add your handling code here:
	}                                     

	private void reactor5MouseClicked(java.awt.event.MouseEvent evt) {                                      
		// TODO add your handling code here:
	}                                     

	private void tanqueCeraMouseClicked(java.awt.event.MouseEvent evt) {                                        
		// TODO add your handling code here:
	}                                       

	private void tanqueEstearinaMouseClicked(java.awt.event.MouseEvent evt) {                                             
		// TODO add your handling code here:
	}                                            

	private void molino1MouseClicked(java.awt.event.MouseEvent evt) {                                     
		// TODO add your handling code here:
	}                                    

	private void rt1MouseClicked(java.awt.event.MouseEvent evt) {                                 
		// TODO add your handling code here:
	}                                

	private void criba2MouseClicked(java.awt.event.MouseEvent evt) {                                     
		// TODO add your handling code here:
	}                                    

	private void molino5MouseClicked(java.awt.event.MouseEvent evt) {                                     
		// TODO add your handling code here:
	}                                    

	// Variables declaration - do not modify                     
	private javax.swing.JButton criba2;
	private javax.swing.Box.Filler filler1;
	private javax.swing.JButton molino1;
	private javax.swing.JButton molino5;
	private javax.swing.JButton pelletizador;
	private javax.swing.JButton reactor1;
	private javax.swing.JButton reactor2;
	private javax.swing.JButton reactor3;
	private javax.swing.JButton reactor4;
	private javax.swing.JButton reactor5;
	private javax.swing.JButton rt1;
	private javax.swing.JButton tanqueCera;
	private javax.swing.JButton tanqueEstearina;
	// End of variables declaration 

	Form form;
	javax.swing.JTextField batch;
	javax.swing.JList productos;
	ButtonPrompt buttonPrompt;
	Controller controller;
}
